# Generated by Django 3.1.4 on 2020-12-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoxs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangox',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
